# permissions for end users to view maasvalidators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: maasvalidator-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: validator-plugin-maas
    app.kubernetes.io/part-of: validator-plugin-maas
    app.kubernetes.io/managed-by: kustomize
  name: maasvalidator-viewer-role
rules:
- apiGroups:
  - validation.spectrocloud.labs
  resources:
  - maasvalidators
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - validation.spectrocloud.labs
  resources:
  - maasvalidators/status
  verbs:
  - get
