# permissions for end users to edit ocivalidators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: ocivalidator-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: validator-plugin-maas
    app.kubernetes.io/part-of: validator-plugin-maas
    app.kubernetes.io/managed-by: kustomize
  name: ocivalidator-editor-role
rules:
- apiGroups:
  - validation.spectrocloud.labs
  resources:
  - ocivalidators
  - validationresults
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - validation.spectrocloud.labs
  resources:
  - ocivalidators/status
  - validationresults/status
  verbs:
  - get
