name: GoLicenses

on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: golicenses-${{ github.ref }}
  cancel-in-progress: true

jobs:
  golicense-pr-scan:
    runs-on: [self-hosted, Linux, X64, validator]
    steps:
      - name: install-git
        run: sudo apt-get install -y git

      - name: checkout
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4

      - name: Set up Go
        uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5
        with:
          go-version-file: go.mod

      - name: install-golicenses
        run: go install github.com/google/go-licenses@v1.6.0

      - name: golicense-scan
        run: |
          go-licenses check ./...
